<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KullaniciIslemleri</name>
   <tag></tag>
   <elementGuidId>90a04949-db70-457b-b620-128e17d50d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dropdown>a>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dropdown>a>img</value>
   </webElementProperties>
</WebElementEntity>
