<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DosyaYukle</name>
   <tag></tag>
   <elementGuidId>0f58192a-5203-4658-a2d1-75cf45698d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxucTextBox_LECustomTheme.dxucNullText_LECustomTheme>input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxucTextBox_LECustomTheme.dxucNullText_LECustomTheme>input</value>
   </webElementProperties>
</WebElementEntity>
