<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YuklemeyiBaslat</name>
   <tag></tag>
   <elementGuidId>1c6ee6bc-5fa8-41b2-9b06-26a5e4091086</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.btn.btn-success.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.btn.btn-success.btn-sm</value>
   </webElementProperties>
</WebElementEntity>
