<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>YuklemeKontrolu</name>
   <tag></tag>
   <elementGuidId>9e905050-6652-41dc-b82b-ebf06b84630f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#uploadedFiles>tr>td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#uploadedFiles>tr>td</value>
   </webElementProperties>
</WebElementEntity>
