<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopupOK</name>
   <tag></tag>
   <elementGuidId>006e06ca-0b03-4d42-874b-e8722045bbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.btn.btn-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.btn.btn-success</value>
   </webElementProperties>
</WebElementEntity>
