<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ekle</name>
   <tag></tag>
   <elementGuidId>441d9a7c-b84c-4ed7-9f4a-ac47ea0e608e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//img</value>
   </webElementProperties>
</WebElementEntity>
