<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RolCheckBox</name>
   <tag></tag>
   <elementGuidId>2caf1c41-5ee6-4b4e-9e11-d96aa4e61a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//span</value>
   </webElementProperties>
</WebElementEntity>
