<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alanlar</name>
   <tag></tag>
   <elementGuidId>cdb6fc21-bdf2-41d9-8ba1-eb51202c25a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.control-label.paddingMarginRLC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.control-label.paddingMarginRLC</value>
   </webElementProperties>
</WebElementEntity>
