<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown</name>
   <tag></tag>
   <elementGuidId>0280c755-183f-46e6-8d14-4d851481247e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../..//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../..//select</value>
   </webElementProperties>
</WebElementEntity>
