<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textbox</name>
   <tag></tag>
   <elementGuidId>bf02e595-92a8-453a-b901-2d43fe501896</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../..//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../..//input</value>
   </webElementProperties>
</WebElementEntity>
