<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KapaliKutular</name>
   <tag></tag>
   <elementGuidId>5c9aa811-c6d6-4948-a2e0-d2afef6278f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxnb-headerCollapsed>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxnb-headerCollapsed>span</value>
   </webElementProperties>
</WebElementEntity>
