<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EklenenSatirCarpiImage</name>
   <tag></tag>
   <elementGuidId>e80deed8-1422-46ae-9c07-3e74d9979f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.fa.fa-times.fa-lg.text-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.fa.fa-times.fa-lg.text-primary</value>
   </webElementProperties>
</WebElementEntity>
