<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Firma_Secimi_Checkbox</name>
   <tag></tag>
   <elementGuidId>e6cd4d16-4f82-4380-abc2-834d9d43e7e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../td/span</value>
   </webElementProperties>
</WebElementEntity>
