<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkbox</name>
   <tag></tag>
   <elementGuidId>4ac6b4c5-4e63-4c7c-b381-977b3a501d16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../a/i</value>
   </webElementProperties>
</WebElementEntity>
