<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tree</name>
   <tag></tag>
   <elementGuidId>b6f0f487-418d-4663-80c2-acfa85daa235</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//i</value>
   </webElementProperties>
</WebElementEntity>
