<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basliga_Gore_Baslangic_Image</name>
   <tag></tag>
   <elementGuidId>4f483e89-fea7-47b3-a34c-09a41887e9e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../div[1]//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../div[1]//img</value>
   </webElementProperties>
</WebElementEntity>
