<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basliga_Gore_Dropdown</name>
   <tag></tag>
   <elementGuidId>4e6af6ff-cb20-401c-8aaf-f1e8bd6689a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//td[2]/input</value>
   </webElementProperties>
</WebElementEntity>
