<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Basliga_Gore_Bitis_Image</name>
   <tag></tag>
   <elementGuidId>f1013020-7030-4cab-9e82-91cc36a8fd84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../div[2]//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../div[2]//img</value>
   </webElementProperties>
</WebElementEntity>
