<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GorselTasarimBaslik</name>
   <tag></tag>
   <elementGuidId>42da12bb-e8d3-428f-be67-c0a7f4e12c27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#flAlici_0>div>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#flAlici_0>div>span</value>
   </webElementProperties>
</WebElementEntity>
