<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AyarlarBasliklar</name>
   <tag></tag>
   <elementGuidId>f106faa4-4755-473b-a526-076e5f3b80b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxnb-header>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxnb-header>span</value>
   </webElementProperties>
</WebElementEntity>
