<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DuzenlemeFormuTextBox</name>
   <tag></tag>
   <elementGuidId>422f99e1-f258-42c8-8ad7-7907585ee3c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../..//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../..//input</value>
   </webElementProperties>
</WebElementEntity>
