<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kaydet</name>
   <tag></tag>
   <elementGuidId>8b79a2d7-66ad-4422-aa51-065ad35da29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#btnSaveRole_CD>span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#btnSaveRole_CD>span</value>
   </webElementProperties>
</WebElementEntity>
