<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Klasorler</name>
   <tag></tag>
   <elementGuidId>d0c67687-3bd0-4b35-a71f-14f2d39378df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxtl.dxtl__B0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxtl.dxtl__B0</value>
   </webElementProperties>
</WebElementEntity>
