<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KlasorAc</name>
   <tag></tag>
   <elementGuidId>481253b7-d34d-4a1c-82fa-952e6a8aff63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//img</value>
   </webElementProperties>
</WebElementEntity>
