<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>KlasorSec</name>
   <tag></tag>
   <elementGuidId>484d9933-a920-485b-9487-d883198604d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//input</value>
   </webElementProperties>
</WebElementEntity>
