<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerininCheckBoxi</name>
   <tag></tag>
   <elementGuidId>1d84d117-ce15-43e7-8346-2bd632866a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>ancestor::tr[1]//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>ancestor::tr[1]//span</value>
   </webElementProperties>
</WebElementEntity>
