<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerininButonu</name>
   <tag></tag>
   <elementGuidId>7ecfe180-8a95-451f-9de5-6bb1b3059570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>ancestor::tr[1]//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>ancestor::tr[1]//a</value>
   </webElementProperties>
</WebElementEntity>
