<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>VerininYanindakiTextler</name>
   <tag></tag>
   <elementGuidId>d6d34b30-bf51-4ac2-83c7-f94cceff4299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>../descendant::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>../descendant::*</value>
   </webElementProperties>
</WebElementEntity>
