<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DepartmanCheckboxi</name>
   <tag></tag>
   <elementGuidId>bf504043-158a-4e28-a3a6-3bf2fec4c351</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dx-wrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dx-wrap</value>
   </webElementProperties>
</WebElementEntity>
