<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DepartmanKaydetButoni</name>
   <tag></tag>
   <elementGuidId>08f23930-9869-428d-8b7e-296c9ce1afce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dx-vam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dx-vam</value>
   </webElementProperties>
</WebElementEntity>
