<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GecmisBaslik</name>
   <tag></tag>
   <elementGuidId>4dcfab4c-7760-4177-aa25-16691a0694c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxnb-ghtext.dx-vam</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxnb-ghtext.dx-vam</value>
   </webElementProperties>
</WebElementEntity>
