<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Olusturma_Goster_Baslik</name>
   <tag></tag>
   <elementGuidId>d409b8d7-5f93-4028-8fa2-74ac0193527c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>h1>span,td>font,font</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>h1>span,td>font,font</value>
   </webElementProperties>
</WebElementEntity>
