<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UBLTag</name>
   <tag></tag>
   <elementGuidId>03ba2bcb-f06c-4ebd-a9d9-cb8d8dc8fb7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#webkit-xml-viewer-source-xml>:first-child</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#webkit-xml-viewer-source-xml>:first-child</value>
   </webElementProperties>
</WebElementEntity>
