<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alici_Adi</name>
   <tag></tag>
   <elementGuidId>c602d3b1-fdf2-48ff-9d37-a295b62a7a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>#GridViewCustomer_DXMainTable>tbody>tr.dxgvDataRow_LECustomTheme>td:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#GridViewCustomer_DXMainTable>tbody>tr.dxgvDataRow_LECustomTheme>td:nth-child(2)</value>
   </webElementProperties>
</WebElementEntity>
