<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bosluk</name>
   <tag></tag>
   <elementGuidId>7b155dde-5cae-4f77-8234-782d56c2e26e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxgvCommandColumn_LECustomTheme.dxgv.dx-ac</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxgvCommandColumn_LECustomTheme.dxgv.dx-ac</value>
   </webElementProperties>
</WebElementEntity>
