<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sil</name>
   <tag></tag>
   <elementGuidId>43ad0292-d839-492e-8dfc-0b7fc40b117f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.fa.fa-trash-o.fa-lg.text-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.fa.fa-trash-o.fa-lg.text-danger</value>
   </webElementProperties>
</WebElementEntity>
