<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>malzeme</name>
   <tag></tag>
   <elementGuidId>ef02919e-7abf-48c7-ac96-e04ca0a4a1bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.dxgvDataRow_LECustomTheme>td:nth-child(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.dxgvDataRow_LECustomTheme>td:nth-child(2)</value>
   </webElementProperties>
</WebElementEntity>
