<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SablonButonlari</name>
   <tag></tag>
   <elementGuidId>ee2d75ad-3ec2-48cc-8ca5-c14212c3636c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>..//a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>..//a</value>
   </webElementProperties>
</WebElementEntity>
