<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kapat</name>
   <tag></tag>
   <elementGuidId>31913292-2ae7-43db-a6aa-108bda97cbe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.bootbox-close-button.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.bootbox-close-button.close</value>
   </webElementProperties>
</WebElementEntity>
