<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Butons</name>
   <tag></tag>
   <elementGuidId>9f6c4c38-a47a-4f2f-bda9-b88c710d56b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.modal-footer>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.modal-footer>button</value>
   </webElementProperties>
</WebElementEntity>
