<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup</name>
   <tag></tag>
   <elementGuidId>ec361219-cefe-4d10-aa61-ae8038144968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.bootbox-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.bootbox-body</value>
   </webElementProperties>
</WebElementEntity>
